import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import { Providers } from "@/app/[locale]/Providers";

import { NextIntlClientProvider, useMessages } from "next-intl";

const poppins = Poppins({ subsets: ["latin"], weight: ["100", "200", "300","400", "500","600","700", "800", "900"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = useMessages();
  return (
    <html lang={locale}>
      <body className={poppins.className}>
        <Header />
        <main className="p-2 md:p-10">
          <Providers>
              <NextIntlClientProvider locale={locale} messages={messages}>
                <main>{children}</main>
              </NextIntlClientProvider>
          </Providers>
        </main>
      </body>
    </html>
  );
}